### ISSUE TITLE
Object.entries

### ISSUE THREAD

**Issue by liangzq1** [xiaoyao96/wxMiniStore#25]
请问怎样在mystore.js，method方法中修改state中的值，其他页面调用这个方法

**Comment by zkl2333** [comment]
```javascript
getApp().store.setState({
       msg: "我被修改了，呜呜..."
    });
```

**Comment by liangzq1** [comment]
还有一个问题呃。小程序在真机和编辑器上运行都正常，上传到体验版就报Object.entries语法错误，我搜了一下全局，只有store.js中有用到Object.entries，请麻烦帮忙看看什么问题阿。。。
thirdScriptError
Object.entries is not a function. (In 'Object.entries(c)', 'Object.entries' is undefined);at api request success callback function
at o (app-service.js:3034:554)
at r (app-service.js:3034:274)
at value (app-service.js:3034:5387)
at success (app-service.js:3073:3566)
at success (app-service.js:3019:853)
at (WASubContext.js:2:1313158)
at (WAServiceMainContext.js:2:127544)
at E (WASubContext.js:2:420308)
at (WASubContext.js:2:799661)
at emit (WASubContext.js:2:478421)
at rs (WASubContext.js:2:800527)
at (WASubContext.js:2:801806)
at (WASubContext.js:2:463395)
at (WAServiceMainContext.js:2:225318)
at _ (WAServiceMainContext.js:2:77637)
global code

**Comment by zkl2333** [comment]
开启转es6和增强编译



---原始邮件---
发件人: "liangzq1"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 晚上11:19
收件人: "xiaoyao96/wxMiniStore"<wxMiniStore@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"zkl2333"<zkl2333@qq.com&gt;;
主题: Re: [xiaoyao96/wxMiniStore] 请问怎样在mystore.js，method方法中修改state中的值，其他页面调用这个方法 (#25)




 
还有一个问题呃。小程序在真机和编辑器上运行都正常，上传到体验版就报Object.entries语法错误，我搜了一下全局，只有store.js中有用到Object.entries，请麻烦帮忙看看什么问题阿。。。
 thirdScriptError
 Object.entries is not a function. (In 'Object.entries(c)', 'Object.entries' is undefined);at api request success callback function
 at o (app-service.js:3034:554)
 at r (app-service.js:3034:274)
 at value (app-service.js:3034:5387)
 at success (app-service.js:3073:3566)
 at success (app-service.js:3019:853)
 at (WASubContext.js:2:1313158)
 at (WAServiceMainContext.js:2:127544)
 at E (WASubContext.js:2:420308)
 at (WASubContext.js:2:799661)
 at emit (WASubContext.js:2:478421)
 at rs (WASubContext.js:2:800527)
 at (WASubContext.js:2:801806)
 at (WASubContext.js:2:463395)
 at (WAServiceMainContext.js:2:225318)
 at _ (WAServiceMainContext.js:2:77637)
 global code

**Comment by liangzq1** [comment]
好的我试试，谢谢

> 开启转es6和增强编译
> […](#)
> ---原始邮件--- 发件人: "liangzq1"<notifications@github.com&gt; 发送时间: 2020年4月24日(周五) 晚上11:19 收件人: "xiaoyao96/wxMiniStore"<wxMiniStore@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"zkl2333"<zkl2333@qq.com&gt;; 主题: Re: [xiaoyao96/wxMiniStore] 请问怎样在mystore.js，method方法中修改state中的值，其他页面调用这个方法 (#25) 还有一个问题呃。小程序在真机和编辑器上运行都正常，上传到体验版就报Object.entries语法错误，我搜了一下全局，只有store.js中有用到Object.entries，请麻烦帮忙看看什么问题阿。。。 thirdScriptError Object.entries is not a function. (In 'Object.entries(c)', 'Object.entries' is undefined);at api request success callback function at o (app-service.js:3034:554) at r (app-service.js:3034:274) at value (app-service.js:3034:5387) at success (app-service.js:3073:3566) at success (app-service.js:3019:853) at (WASubContext.js:2:1313158) at (WAServiceMainContext.js:2:127544) at E (WASubContext.js:2:420308) at (WASubContext.js:2:799661) at emit (WASubContext.js:2:478421) at rs (WASubContext.js:2:800527) at (WASubContext.js:2:801806) at (WASubContext.js:2:463395) at (WAServiceMainContext.js:2:225318) at _ (WAServiceMainContext.js:2:77637) global code — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xiaoyao96** [comment]
看来我有必要把Object.entries给弄个polyfill..下个版本加吧...

**Comment by zkl2333** [comment]
> 看来我有必要把Object.entries给弄个polyfill..下个版本加吧...

你已经十八天没有commit了

**Comment by xiaoyao96** [comment]
> > 看来我有必要把Object.entries给弄个polyfill..下个版本加吧...
> 
> 你已经十八天没有commit了

太忙了最近。今天闲下来，改了我另一个px-parser项目。剩下的时间让我养养头发先... 这个issues我打个标签先
